### ISSUE TITLE
New CLHM release

### ISSUE THREAD

**Issue by travier** [coreos/console-login-helper-messages#108]
Make a new release to include latest fixes from https://github.com/coreos/console-login-helper-messages/pull/103 and push RPM packages update.

**Comment by dustymabe** [comment]
Hold this. We've got one more change (for SELinux) to make that will help to fix https://github.com/coreos/fedora-coreos-tracker/issues/1153

**Comment by travier** [comment]
Closing this one as the new CLHM is in Fedora now.
