### ISSUE TITLE
issuegen should not run via udev rule when disbaled via systemd

### ISSUE THREAD

**Issue by sheesupport** [coreos/console-login-helper-messages#48]
While porting this to RHEL8 I noticed following, briefly:

issuegen runs even when disabled 

```
# systemctl is-enabled console-login-helper-messages-issuegen
disabled
```

but 

```
# ls -la /run/console-login-helper-messages/40_console-login-helper-messages.issue 
-rw-r--r--. 1 root root 255 14. Mai 21:47 /run/console-login-helper-messages/40_console-login-helper-messages.issue
```

because

`/usr/lib/udev/rules.d/90-console-login-helper-messages-issuegen.rules`

passes the systemd state.

So,

`/usr/libexec/console-login-helper-messages/issuegen`

should check "is-enabled" or is executed manually via systemctl start.

**Comment by rfairley** [comment]
Thank you for catching this! Had been planning to split out part of the script in https://github.com/coreos/console-login-helper-messages/pull/43 which will also avoid the improper execution of issuegen. Short-term, the check on "is-enabled" would be good - but will try to land #43 first to fix this.
