### ISSUE TITLE
Add CI/automated testing to the master branch of this repository

### ISSUE THREAD

**Issue by rfairley** [coreos/console-login-helper-messages#5]
Automated testing by installing the `console-login-helper-messages*` packages on a vanilla `{Fedora/Atomic/CentOS}` system, starting the systemd units, and checking that the expected output is produced at login (by `sshd` for motd, `agetty` for issue,  and by the bash terminal for `profile`) would save time manual testing this.

A build of the RPMs, an install, and a test run should trigger once when a PR is opened.

**Comment by rfairley** [comment]
Example of basic tests that can be automated: https://github.com/rfairley/console-login-helper-messages/blob/0d6b9c89e3c210640a943d3bae29484ef094cc24/reviewers.md

**Comment by rfairley** [comment]
#32 drops a Vagrantfile that provisions a VM with this package installed. This approach could be used in CI.

**Comment by rfairley** [comment]
One approach now is to have `kola` external tests, which `coreos-assembler` can run either in development or testing environments: https://github.com/coreos/coreos-assembler/blob/master/mantle/kola/README-kola-ext.md

Then the command https://github.com/coreos/coreos-assembler/blob/master/src/cmd-build-fast could be used for local development.

Example of a pipeline:
https://github.com/coreos/ignition-dracut/blob/master/.cci.jenkinsfile

This would require adding a `make install` target, similar to:
https://github.com/coreos/ignition-dracut/blob/master/Makefile

We'd also want to unify the `make install` target with the CLHM RPM specfile at https://src.fedoraproject.org/rpms/console-login-helper-messages/blob/master/f/console-login-helper-messages.spec, to avoid multiple sources of truth.

**Comment by kelvinfan001** [comment]
Closed by https://github.com/coreos/console-login-helper-messages/pull/75
