### ISSUE TITLE
Failed systemd units' names not showing in Fedora 33

### ISSUE THREAD

**Issue by kelvinfan001** [coreos/console-login-helper-messages#81]
On FCOS F33, after login, the names of the failed systemd units are not shown properly:
```
[core@cosa-devsh system]$ bash
[systemd]
Failed Units: 3
  ●
  ●
  ●
```

**Comment by dustymabe** [comment]
Yeah I notice this too on Fedora Cloud base image and also on my Desktop. I have no idea why.

**Comment by dustymabe** [comment]
but yeah, obviously something that we'd like to get fixed ideally in the next week before Fedora 33 freezes so that our cloud base image doesn't have that issue.

**Comment by kelvinfan001** [comment]
This bug is caused by a change in the format of the output of `systemctl list-units`.
